dist: xenial
language: node_js
node_js:
  - '11'

# Deploying uses awscli and it uses Python.
# Xenial on Travis comes with Python 2 & 3 installed but 2 is default.
# Ensure pip3 is installed and upgraded.
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install python3-pip
  - sudo -H pip3 install --upgrade pip

script:
  # will run `npm ci` automatically here
  - npm test
  - 'if [ "$TRAVIS_SECURE_ENV_VARS" = "true" ]; then npm run build; fi'

after_success:
  - pip3 install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - npm run deploy

notifications:
  email: false

cache:
  npm: true
  directories:
    - public
